### PR TITLE
Add an "interactive" option

### LINKED ISSUE #37: Feature: Interactive remove of unused packages
After listing the unused packages, there should be an interactive mode to remove unused packages.

**Describe the solution you'd like**
After finding unused packages the user should get asked what to do with unused packages:
- remove
- skip
- ignore (should be added to `composer.json` `extra` for ignore)

**Additional information**
This kind of behavior should be optional and might be enabled with a cli parameter `--interactive`. Using an opt-in parameter this should not interfere with CI usage of this tool.

### PR DESCRIPTION
**Pull request by varunsingh87**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/composer-unused/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

**Closes #37**

### CODE REVIEW

**Comment by Borumer** [comment]
The `CONTRIBUTING.MD` says to run `$ composer global require icanhazstring/composer-unused:dev-feature/awesome`
so I ran `composer global require borumer/composer-unused:borumer-37` (because my branch is only on my fork) I also switched the first borumer with `icanhazstring` but that also didn't work. 
I need to test to see what my code is doing. What do I do?

**Comment by Borumer** [comment]
I have finished the interactive command but I do have a few review questions:
- I had to update the composer.json file to include the directive. Was I just supposed to use PHP's file_get_contents and file_put_contents or is there a safer way of doing this?
- I wrote around 40 lines of code. Should I put this in a separate class or leave it in UnusedCommand.php? If the former, I would be able to easily write tests for the new feature.
- Is there anything I need to add/remove/change?

This pull request implements the feature request described in issue #37 

> After finding unused packages the user should get asked what to do with unused packages:

**Comment by icanhazstring** [comment]
> The `CONTRIBUTING.MD` says to run `$ composer global require icanhazstring/composer-unused:dev-feature/awesome`
> so I ran `composer global require borumer/composer-unused:borumer-37` (because my branch is only on my fork) I also switched the first borumer with `icanhazstring` but that also didn't work. 
> I need to test to see what my code is doing. What am I missing?

You can also just run the `bin/console` command and run it against composer-unused itself. This is a easier way to check if everything is working. For this you need to add a any unused package as a requirement first.

**Comment by icanhazstring** [comment]
Hi, @Borumer thanks for the contribution so far.
I didn't find the time yet for getting a full review. I will try to squeeze in some time to add information on how to further optimize your implementation which looks great at first sight.

**Comment by Borumer** [comment]
> You can also just run the `bin/console` command and run it against composer-unused itself. This is a easier way to check if everything is working. For this you need to add a any unused package as a requirement first.

Thanks, `bin/composer-unused unused --interactive` worked. From my code, the `skip` and `remove` options work, while the `ignore` option I need some help with. I currently use the following code, which is obviously problematic (for one, I get an error opening a stream to /composer.json, and I can't find any command I can run to add something to the composer.json file. 

    // Add package name to unused property of extras directive in composer.json
    $composerJsonContents = file_get_contents("/composer.json");
    $composerJsonContents = json_decode($composerJsonContents, true);
    $extraDirectiveUnusedArr = $composerJsonContents["extra"]["unused"];
    if (in_array($packageName, $extraDirectiveUnusedArr)) {
        array_push(
            $extraDirectiveUnusedArr,
            $packageName
         );
    }
    $newContents = json_encode($composerJsonContents);
    file_put_contents('/composer.json', $newContents);
    break;

**Comment by Borumer** [comment]
> Hi, @Borumer thanks for the contribution so far.
> I didn't find the time yet for getting a full review. I will try to squeeze in some time to add information on how to further optimize your implementation which looks great at first sight.

Thanks! I look forward to the review!

**Comment by Borumer** [comment]
Hi, happy new year! I just wanted to follow up about this pull request submission. 

I am excited to make more contributions to this project once this pull request is complete 🙌

**Comment by icanhazstring** [comment]
Hi @Borumer, Thanks!
Same to you as well.

As I am at the finished line for moving to my new house, I didn't found the appropriate time to review your submission.

I will try to squeeze in some time for you so we can move forward 👍

Thanks for your patience 🙏

**Comment by varunsingh87** [comment]
I saw you were active on this repository so I was wondering if we could now move forward with this pull request.

**Comment by icanhazstring** [comment]
Hi @varunsingh87 sorry for this late response.
Yes we should definitely get this implemented :)

I have updated the `main` branch with a code refactoring.
If you need any further help to get going, hit me up.

**Pull request closed without merging**
