### PR TITLE
Add JsonFormatter with test

### PR DESCRIPTION
**Pull request by TomasVotruba**
Follow up to https://github.com/composer-unused/composer-unused/pull/280#issuecomment-1265958116

So other tools can pick up the result easily and parse it to standardized json :+1:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready for review :+1:

**Comment by icanhazstring** [comment]
Awesome. Love it. Thank you 🙏

**Comment by TomasVotruba** [comment]
That was fast, thank you :)

**Comment by TomasVotruba** [comment]
Btw, I'd like to use this in a tool and need the stable tag to easily install it.
Any ETA when you plan to release this?

Thanks :)

**Comment by TomasVotruba** [comment]
Thank you :partying_face: Awesomesauce :hugs:

**Pull request merged**
