### PR TITLE
Issue 534

### PR DESCRIPTION
**Pull request by MarcinGladkowski**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/composer-unused/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by icanhazstring** [comment]
Pretty cool. Thanks 🙂

**Comment by MarcinGladkowski** [comment]
@icanhazstring I'm wondering about not passing two tests on actions. Both tests are using `chdir()` and failing.

It started failing from 2 weeks ago on MR branches.
https://github.com/composer-unused/composer-unused/actions/workflows/validate-code.yml

**Comment by icanhazstring** [comment]
Hm ok. That seems weird. Also that it's only happening with 8.1 and 8.2 but not prior 🤔

Do they work locally?

**Comment by MarcinGladkowski** [comment]
Yes. It's passing locally. That's why I'm debugging manually on Actions. :/

**Comment by icanhazstring** [comment]
That is why I hate debugging actions 😅
Is there maybe some camel casing Problem?

**Comment by icanhazstring** [comment]
Seems that it works now 😅

**Comment by MarcinGladkowski** [comment]
I edited tests which are using `chdir()`. That's why it's started working. Of coruse, I squashed commits.

**Comment by MarcinGladkowski** [comment]
I want to mention besides this problem I checked carefully code generated by Composer and I don't see any other way to check which Composer Version was used to install packages.

**Comment by icanhazstring** [comment]
Thanks for the addition 💪

**Comment by MarcinGladkowski** [comment]
It's pleasure for me. Have a nice day :smile:

**Pull request merged**
