### PR TITLE
Exclude .phive from exported artefacts

### PR DESCRIPTION
**Pull request by theofidry**
Indeed the .phive artefact contains `.phive/box` which is quite heavy (from a package size perspective) and to be honest I also wonder if it (the PHAR(s))should really be committed within git at all instead of being installed by phive.

### CODE REVIEW

**Comment by icanhazstring** [comment]
Good catch. And yes, the phar should not be committed.

Can you place a gitignore ignoring everything except phive.xml?

**Comment by theofidry** [comment]
done

**Comment by icanhazstring** [comment]
We probably have to adjust https://github.com/composer-unused/composer-unused/blob/main/.github/workflows/release-phar.yml#L45 as well to install box using phive before packing the release.

**Comment by icanhazstring** [comment]
`.phive` folder not longer present in project.

**Pull request closed without merging**
