### PR TITLE
Add --output-format

### LINKED ISSUE #279: Feature: Add output format option
Add ability to change output format

_Originally posted by @icanhazstring in https://github.com/composer-unused/composer-unused/discussions/272#discussioncomment-1990032_

### PR DESCRIPTION
**Pull request by icanhazstring**
Resolve #279 

/cc @MGatner

### CODE REVIEW

**Comment by MGatner** [comment]
Without `--profile` it seems to be working! I'm not familiar with the GitHub format but I assume this is expected:
```bash
~/composer-unused/bin/composer-unused -vvv --output-format=github --ansi --no-interaction --no-progress --excludePackage=php

::error file=/opt/codeigniter4/files/composer.json,line=24,col=0::enyo/dropzone is unused
::error file=/opt/codeigniter4/files/composer.json,line=25,col=0::tatter/alerts is unused
::error file=/opt/codeigniter4/files/composer.json,line=29,col=0::tatter/preferences is unused
```

**Comment by icanhazstring** [comment]
Could be that `--profile` was an option from composer. So if it was executrd as a composer plugin this option was available.

But for composer-unused itself this option never existed.

**Comment by MGatner** [comment]
Weird! I wasn't aware of that interaction with Composer. Once this feature is live we wouldn't want profile output in our GitHub Actions output format anyways, so I'll start pulling those. Thanks!

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
🥳

**Comment by TomasVotruba** [comment]
Thanks for this feature :+1: 
I want to use JSON output to pass data to another tool. But it seems hardcoded... how can I add a new output formatter?

**Comment by icanhazstring** [comment]
@TomasVotruba you can add a new case here

https://github.com/composer-unused/composer-unused/blob/main/src/OutputFormatter/FormatterFactory.php#L33

And add a new Implementation alongside the GithubFormatter.

**Comment by TomasVotruba** [comment]
@icanhazstring Allright :) 
See the json formatter here: https://github.com/composer-unused/composer-unused/pull/398

**Comment by MGatner** [comment]
@TomasVotruba?! Here?? 😍😍

**Pull request merged**
