### PR TITLE
Add symfony 7 support

### PR DESCRIPTION
**Pull request by VincentLanglet**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/composer-unused/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

Hi @icanhazstring ; Symfony 7 is now in RC mode.
Some library are trying to add support for it, and adding support to this one would be helpful.

Thanks a lot for your consideration :)

### CODE REVIEW

**Comment by icanhazstring** [comment]
Thanks 🙏🚀

**Comment by VincentLanglet** [comment]
You're welcome. Do you have time to create a new release ? :)

**Comment by VincentLanglet** [comment]
Hi @icanhazstring Would it be ok to create a new release with SF 7 support ? Thanks

**Comment by icanhazstring** [comment]
Sure, will probably take a release in the next day or two 👍

**Comment by icanhazstring** [comment]
Done. Hope everything works :)

**Pull request merged**
